import type { Product, Collection, UGCPost, LookbookItem, BundleHotspot } from "./types";

// Helper to create placeholder images from picsum / unsplash with seed
function img(seed: string, w = 800, h = 1000) {
  // Using picsum seeded
  return `https://picsum.photos/seed/${seed}/${w}/${h}`;
}

export const products: Product[] = [
  {
    id: "prod_1",
    handle: "terracotta-suede-sandals",
    title: "Terracotta Suede Sandals",
    description: "Sun-bleached suede sandals with hand-stitched detailing. Barefoot-light, all-day comfort.",
    descriptionHtml: "<p>Sun-bleached suede sandals with hand-stitched detailing. Barefoot-light, all-day comfort. Lined with soft leather and finished with a woven jute sole.</p>",
    vendor: "Coastal Aesthetic",
    productType: "Footwear",
    tags: ["suede", "terracotta", "handcrafted"],
    category: "footwear",
    material: "Suede",
    priceRange: { minVariantPrice: { amount: "89.00", currencyCode: "USD" } },
    featuredImage: { url: img("sandals-hero", 800, 1000), altText: "Model wearing terracotta suede sandals on a sandy beach at golden hour", width: 800, height: 1000 },
    images: [
      { url: img("sandals-hero", 800, 1000), altText: "Model wearing terracotta suede sandals on a sandy beach at golden hour", width: 800, height: 1000 },
      { url: img("sandals-side", 800, 1000), altText: "Side profile of terracotta suede sandals showing woven jute sole", width: 800, height: 1000 },
      { url: img("sandals-detail", 800, 1000), altText: "Close-up detail of hand-stitched terracotta suede strap", width: 800, height: 1000 },
      { url: img("sandals-lifestyle", 1200, 800), altText: "Woman walking on a beach boardwalk wearing terracotta suede sandals with linen dress", width: 1200, height: 800 },
    ],
    variants: [
      { id: "var_1_35", title: "Sand / 35", price: "89.00", availableForSale: true, selectedOptions: [{ name: "Color", value: "Sand" }, { name: "Size", value: "35" }] },
      { id: "var_1_36", title: "Sand / 36", price: "89.00", availableForSale: true, selectedOptions: [{ name: "Color", value: "Sand" }, { name: "Size", value: "36" }] },
      { id: "var_1_37", title: "Terracotta / 37", price: "89.00", availableForSale: true, selectedOptions: [{ name: "Color", value: "Terracotta" }, { name: "Size", value: "37" }] },
      { id: "var_1_38", title: "Terracotta / 38", price: "89.00", availableForSale: false, selectedOptions: [{ name: "Color", value: "Terracotta" }, { name: "Size", value: "38" }] },
    ],
    options: [
      { name: "Color", values: ["Sand", "Terracotta", "Driftwood"] },
      { name: "Size", values: ["35", "36", "37", "38", "39", "40"] },
    ],
    availableForSale: true,
    rating: { value: 4.8, count: 124 },
    videoUrl: "https://picsum.photos/seed/sandals-video/800/1000",
  },
  {
    id: "prod_2",
    handle: "riviera-bow-sun-hat",
    title: "Riviera Bow Sun Hat",
    description: "Fine woven straw hat with a soft bow — shade that breathes.",
    descriptionHtml: "<p>Fine woven straw hat with a soft bow — shade that breathes. Hand-braided palm straw, lightweight and packable.</p>",
    vendor: "Coastal Aesthetic",
    productType: "Hats",
    tags: ["straw", "riviera", "packable"],
    category: "hats",
    material: "Fine Woven Straw",
    priceRange: { minVariantPrice: { amount: "62.00", currencyCode: "USD" } },
    featuredImage: { url: img("hat-hero", 800, 1000), altText: "Woman wearing riviera bow sun hat made of fine woven straw on a beach", width: 800, height: 1000 },
    images: [
      { url: img("hat-hero", 800, 1000), altText: "Woman wearing riviera bow sun hat made of fine woven straw on a beach", width: 800, height: 1000 },
      { url: img("hat-back", 800, 1000), altText: "Back view of riviera bow sun hat showing hand-braided straw texture", width: 800, height: 1000 },
      { url: img("hat-detail", 800, 1000), altText: "Detail of woven straw and linen bow on riviera sun hat", width: 800, height: 1000 },
    ],
    variants: [
      { id: "var_2_os_natural", title: "Natural / One Size", price: "62.00", availableForSale: true, selectedOptions: [{ name: "Color", value: "Natural" }, { name: "Size", value: "One Size" }] },
      { id: "var_2_os_sand", title: "Sand / One Size", price: "62.00", availableForSale: true, selectedOptions: [{ name: "Color", value: "Sand" }, { name: "Size", value: "One Size" }] },
    ],
    options: [
      { name: "Color", values: ["Natural", "Sand", "Terracotta"] },
      { name: "Size", values: ["One Size"] },
    ],
    availableForSale: true,
    rating: { value: 4.9, count: 89 },
  },
  {
    id: "prod_3",
    handle: "sahara-straw-tote",
    title: "Sahara Straw Tote",
    description: "Roomy palm straw tote with leather handles — beach to market.",
    descriptionHtml: "<p>Roomy palm straw tote with leather handles — beach to market. Fits a towel, book, and sun hat with room to spare.</p>",
    vendor: "Coastal Aesthetic",
    productType: "Bags",
    tags: ["straw", "tote", "palm"],
    category: "bags",
    material: "Palm Straw",
    priceRange: { minVariantPrice: { amount: "78.00", currencyCode: "USD" } },
    compareAtPriceRange: { minVariantPrice: { amount: "98.00", currencyCode: "USD" } },
    featuredImage: { url: img("tote-hero", 800, 1000), altText: "Model holding sahara palm straw tote bag with leather handles on a beach dune", width: 800, height: 1000 },
    images: [
      { url: img("tote-hero", 800, 1000), altText: "Model holding sahara palm straw tote bag with leather handles on a beach dune", width: 800, height: 1000 },
      { url: img("tote-inside", 800, 1000), altText: "Interior of sahara straw tote showing roomy linen lining", width: 800, height: 1000 },
      { url: img("tote-lifestyle", 1200, 800), altText: "Sahara straw tote on a striped beach towel beside sandals and hat", width: 1200, height: 800 },
    ],
    variants: [
      { id: "var_3_natural", title: "Natural", price: "78.00", compareAtPrice: "98.00", availableForSale: true, selectedOptions: [{ name: "Color", value: "Natural" }] },
      { id: "var_3_sand", title: "Sand", price: "78.00", availableForSale: true, selectedOptions: [{ name: "Color", value: "Sand" }] },
    ],
    options: [{ name: "Color", values: ["Natural", "Sand"] }],
    availableForSale: true,
    rating: { value: 4.7, count: 203 },
  },
  {
    id: "prod_4",
    handle: "linen-woven-crossbody",
    title: "Linen Woven Crossbody",
    description: "Compact crossbody in sun-faded linen weave.",
    descriptionHtml: "<p>Compact crossbody in sun-faded linen weave. Perfect for hands-free beach walks.</p>",
    vendor: "Coastal Aesthetic",
    productType: "Bags",
    tags: ["linen", "crossbody"],
    category: "bags",
    material: "Linen",
    priceRange: { minVariantPrice: { amount: "54.00", currencyCode: "USD" } },
    featuredImage: { url: img("crossbody", 800, 1000), altText: "Model wearing linen woven crossbody bag in sand color across a beach", width: 800, height: 1000 },
    images: [{ url: img("crossbody", 800, 1000), altText: "Model wearing linen woven crossbody bag in sand color across a beach", width: 800, height: 1000 }],
    variants: [{ id: "var_4", title: "Sand", price: "54.00", availableForSale: true, selectedOptions: [{ name: "Color", value: "Sand" }] }],
    options: [{ name: "Color", values: ["Sand", "Clay"] }],
    availableForSale: true,
  },
  {
    id: "prod_5",
    handle: "dune-braided-sandals",
    title: "Dune Braided Sandals",
    description: "Braided jute sandals with cushioned footbed.",
    descriptionHtml: "<p>Braided jute sandals with cushioned footbed.</p>",
    vendor: "Coastal Aesthetic",
    productType: "Footwear",
    tags: ["jute", "braided"],
    category: "footwear",
    material: "Jute",
    priceRange: { minVariantPrice: { amount: "72.00", currencyCode: "USD" } },
    featuredImage: { url: img("dune-sandals", 800, 1000), altText: "Woman wearing dune braided jute sandals on a white sand beach", width: 800, height: 1000 },
    images: [{ url: img("dune-sandals", 800, 1000), altText: "Woman wearing dune braided jute sandals on a white sand beach", width: 800, height: 1000 }],
    variants: [{ id: "var_5", title: "Natural / 38", price: "72.00", availableForSale: true, selectedOptions: [{ name: "Color", value: "Natural" }, { name: "Size", value: "38" }] }],
    options: [{ name: "Color", values: ["Natural"] }, { name: "Size", values: ["36", "37", "38", "39"] }],
    availableForSale: true,
  },
  {
    id: "prod_6",
    handle: "solstice-wide-brim-hat",
    title: "Solstice Wide-Brim Hat",
    description: "Extra-wide brim straw hat for full sun coverage.",
    descriptionHtml: "<p>Extra-wide brim straw hat for full sun coverage.</p>",
    vendor: "Coastal Aesthetic",
    productType: "Hats",
    tags: ["wide-brim", "straw"],
    category: "hats",
    material: "Palm Straw",
    priceRange: { minVariantPrice: { amount: "85.00", currencyCode: "USD" } },
    featuredImage: { url: img("solstice-hat", 800, 1000), altText: "Model wearing solstice wide-brim palm straw hat with sun flare", width: 800, height: 1000 },
    images: [{ url: img("solstice-hat", 800, 1000), altText: "Model wearing solstice wide-brim palm straw hat with sun flare", width: 800, height: 1000 }],
    variants: [{ id: "var_6", title: "Natural", price: "85.00", availableForSale: true, selectedOptions: [{ name: "Color", value: "Natural" }] }],
    options: [{ name: "Color", values: ["Natural", "Sand"] }],
    availableForSale: true,
  },
  {
    id: "prod_7",
    handle: "coastal-linen-pouch",
    title: "Coastal Linen Pouch",
    description: "Small linen pouch for essentials.",
    descriptionHtml: "<p>Small linen pouch for essentials — fits phone, keys, and lip balm.</p>",
    vendor: "Coastal Aesthetic",
    productType: "Bags",
    tags: ["linen", "pouch"],
    category: "bags",
    material: "Linen",
    priceRange: { minVariantPrice: { amount: "32.00", currencyCode: "USD" } },
    featuredImage: { url: img("pouch", 800, 1000), altText: "Coastal linen pouch in sand color held on a beach towel", width: 800, height: 1000 },
    images: [{ url: img("pouch", 800, 1000), altText: "Coastal linen pouch in sand color held on a beach towel", width: 800, height: 1000 }],
    variants: [{ id: "var_7", title: "Sand", price: "32.00", availableForSale: true, selectedOptions: [{ name: "Color", value: "Sand" }] }],
    options: [{ name: "Color", values: ["Sand", "Natural"] }],
    availableForSale: true,
  },
  {
    id: "prod_8",
    handle: "drift-clay-espadrilles",
    title: "Drift Clay Espadrilles",
    description: "Canvas espadrilles with clay-dyed jute wrap.",
    descriptionHtml: "<p>Canvas espadrilles with clay-dyed jute wrap.</p>",
    vendor: "Coastal Aesthetic",
    productType: "Footwear",
    tags: ["canvas", "espadrille"],
    category: "footwear",
    material: "Canvas",
    priceRange: { minVariantPrice: { amount: "68.00", currencyCode: "USD" } },
    featuredImage: { url: img("espadrilles", 800, 1000), altText: "Pair of drift clay canvas espadrilles with jute soles on a wooden deck", width: 800, height: 1000 },
    images: [{ url: img("espadrilles", 800, 1000), altText: "Pair of drift clay canvas espadrilles with jute soles on a wooden deck", width: 800, height: 1000 }],
    variants: [{ id: "var_8", title: "Clay / 38", price: "68.00", availableForSale: true, selectedOptions: [{ name: "Color", value: "Clay" }, { name: "Size", value: "38" }] }],
    options: [{ name: "Color", values: ["Clay", "Sand"] }, { name: "Size", values: ["36", "37", "38", "39"] }],
    availableForSale: true,
  },
];

export const collections: Collection[] = [
  {
    id: "col_all",
    handle: "shop-all",
    title: "Shop All",
    description: "The full coastal collection — bags, footwear, and hats for sun-bleached days.",
    descriptionHtml: "<p>The full coastal collection — bags, footwear, and hats for sun-bleached days.</p>",
    image: { url: img("col-all", 1200, 800), altText: "Coastal lifestyle flatlay with straw tote, sandals and sun hat", width: 1200, height: 800 },
    products,
  },
  {
    id: "col_bags",
    handle: "beach-bags",
    title: "Beach Bags",
    description: "Woven straw totes, linen crossbodies and sun-faded pouches.",
    descriptionHtml: "<p>Woven straw totes, linen crossbodies and sun-faded pouches.</p>",
    image: { url: img("col-bags", 1200, 800), altText: "Collection of beach bags in natural straw and linen on a beach", width: 1200, height: 800 },
    products: products.filter((p) => p.category === "bags"),
  },
  {
    id: "col_footwear",
    handle: "footwear",
    title: "Footwear",
    description: "Suede sandals, jute braids and canvas espadrilles for sandy walks.",
    descriptionHtml: "<p>Suede sandals, jute braids and canvas espadrilles for sandy walks.</p>",
    image: { url: img("col-footwear", 1200, 800), altText: "Assorted coastal footwear on driftwood", width: 1200, height: 800 },
    products: products.filter((p) => p.category === "footwear"),
  },
  {
    id: "col_hats",
    handle: "sun-hats",
    title: "Sun Hats",
    description: "Wide brims and fine woven straw — breathable shade.",
    descriptionHtml: "<p>Wide brims and fine woven straw — breathable shade.</p>",
    image: { url: img("col-hats", 1200, 800), altText: "Sun hats hanging on a beach house wall with linen shadows", width: 1200, height: 800 },
    products: products.filter((p) => p.category === "hats"),
  },
];

export const ugcPosts: UGCPost[] = Array.from({ length: 8 }).map((_, i) => ({
  id: `ugc_${i}`,
  imageUrl: img(`ugc-${i}`, 600, 600),
  altText: `Customer photo wearing coastal accessories on the beach - UGC post ${i + 1}`,
  author: `@coastal_muse_${i + 1}`,
  caption: "Sun, sand, and my favorite tote ☀️ #CoastalAesthetic",
}));

export const lookbookItems: LookbookItem[] = [
  {
    id: "lb1",
    imageUrl: img("lookbook-1", 1200, 1500),
    altText: "Editorial lookbook photo: model in linen dress with sahara straw tote on a windswept dune",
    title: "Golden Hour Dunes",
    description: "Linen and straw — a study in texture.",
    products: ["sahara-straw-tote", "riviera-bow-sun-hat"],
  },
  {
    id: "lb2",
    imageUrl: img("lookbook-2", 1200, 1500),
    altText: "Lookbook editorial: close-up of terracotta suede sandals on a beach boardwalk",
    title: "Boardwalk Light",
    description: "Hand-stitched suede against sun-bleached wood.",
    products: ["terracotta-suede-sandals"],
  },
  {
    id: "lb3",
    imageUrl: img("lookbook-3", 1200, 1500),
    altText: "Editorial lookbook: woman walking through sea grass wearing solstice wide-brim hat",
    title: "Sea Grass Whisper",
    description: "Wide brim, wide horizon.",
    products: ["solstice-wide-brim-hat"],
  },
  {
    id: "lb4",
    imageUrl: img("lookbook-4", 1200, 1500),
    altText: "Flatlay lookbook: woven bags and sandals arranged on a sand-textured linen cloth",
    title: "The Essentials",
    description: "Curated for the slow, sun-filled escape.",
    products: ["sahara-straw-tote", "dune-braided-sandals", "coastal-linen-pouch"],
  },
];

export const shopTheLookHotspots: BundleHotspot[] = [
  { id: "hs1", x: 35, y: 45, productHandle: "sahara-straw-tote", label: "Sahara Straw Tote" },
  { id: "hs2", x: 52, y: 82, productHandle: "terracotta-suede-sandals", label: "Terracotta Suede Sandals" },
  { id: "hs3", x: 62, y: 22, productHandle: "riviera-bow-sun-hat", label: "Riviera Bow Sun Hat" },
];

export function getProductByHandle(handle: string): Product | undefined {
  return products.find((p) => p.handle === handle);
}
export function getCollectionByHandle(handle: string): Collection | undefined {
  return collections.find((c) => c.handle === handle);
}
